Repository oscar-system/Oscar.jl, pull requests merged in 2023-05, with the labels that each got.

#2342 New naming conventions in PolyhedralGeometry
  docs/src/DeveloperDocumentation/serialization.md
  docs/src/PolyhedralGeometry/Polyhedra/constructions.md
  docs/src/PolyhedralGeometry/fans.md
  docs/src/PolyhedralGeometry/intro.md
  docs/src/PolyhedralGeometry/linear_programs.md
  docs/src/PolyhedralGeometry/mixed_integer_linear_programs.md
  docs/src/PolyhedralGeometry/polyhedral_complexes.md
  docs/src/PolyhedralGeometry/subdivisions_of_points.md
  experimental/FTheoryTools/src/auxiliary.jl
  src/AlgebraicGeometry/ToricVarieties/NormalToricVarieties/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/NormalToricVarieties/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/ToricDivisors/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/ToricMorphisms/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/ToricMorphisms/special_attributes.jl
  src/AlgebraicGeometry/TropicalGeometry/curve.jl
  src/AlgebraicGeometry/TropicalGeometry/groebner_polyhedron.jl
  src/AlgebraicGeometry/TropicalGeometry/hypersurface.jl
  src/AlgebraicGeometry/TropicalGeometry/links.jl
  src/AlgebraicGeometry/TropicalGeometry/variety.jl
  src/Combinatorics/Graphs.jl
  src/Deprecations.jl
  src/Exports.jl
  src/PolyhedralGeometry/Cone/constructors.jl
  src/PolyhedralGeometry/Cone/properties.jl
  src/PolyhedralGeometry/LPFiles.jl
  src/PolyhedralGeometry/LinearProgram.jl
  src/PolyhedralGeometry/MixedIntegerLinearProgram.jl
  src/PolyhedralGeometry/PolyhedralComplex/constructors.jl
  src/PolyhedralGeometry/PolyhedralComplex/properties.jl
  src/PolyhedralGeometry/PolyhedralComplex/standard_constructions.jl
  src/PolyhedralGeometry/PolyhedralFan/constructors.jl
  src/PolyhedralGeometry/PolyhedralFan/properties.jl
  src/PolyhedralGeometry/PolyhedralFan/standard_constructions.jl
  src/PolyhedralGeometry/Polyhedron/constructors.jl
  src/PolyhedralGeometry/Polyhedron/properties.jl
  src/PolyhedralGeometry/Polyhedron/standard_constructions.jl
  src/PolyhedralGeometry/SubdivisionOfPoints/constructors.jl
  src/PolyhedralGeometry/SubdivisionOfPoints/functions.jl
  src/PolyhedralGeometry/SubdivisionOfPoints/properties.jl
  src/PolyhedralGeometry/solving_integrally.jl
  src/PolyhedralGeometry/triangulations.jl
  src/Rings/PBWAlgebra.jl
  src/Rings/groebner.jl
  test/AlgebraicGeometry/ToricVarieties/normal_toric_varieties.jl
  test/PolyhedralGeometry/Cone.jl
  test/PolyhedralGeometry/Group.jl
  test/PolyhedralGeometry/LinearProgram.jl
  test/PolyhedralGeometry/PolyhedralComplex.jl
  test/PolyhedralGeometry/PolyhedralFan.jl
  test/PolyhedralGeometry/Polyhedron.jl
  test/PolyhedralGeometry/SubdivisionOfPoints.jl
  test/PolyhedralGeometry/extended.jl
  test/PolyhedralGeometry/lineality.jl
  test/PolyhedralGeometry/timing.jl
  test/Serialization/PolyhedralGeometry.jl
  test/Serialization/TropicalGeometry.jl
  test/Serialization/containers.jl
  test/Serialization/loading.jl
Labels: enhancement, topic: polytopes, WIP, renaming

#2354 Rename files according to styleguide
  docs/src/DeveloperDocumentation/styleguide.md
  src/Oscar.jl
  src/PolyhedralGeometry/LP_file_format.jl
  src/PolyhedralGeometry/PolyhedralGeometry.jl
  src/PolyhedralGeometry/groups.jl
  src/PolyhedralGeometry/linear_program.jl
  src/PolyhedralGeometry/mixed_integer_linear_program.jl
  src/PolyhedralGeometry/visualization.jl
  src/aliases.jl
  src/deprecations.jl
  src/exports.jl
  test/PolyhedralGeometry/cone.jl
  test/PolyhedralGeometry/group.jl
  test/PolyhedralGeometry/linear_program.jl
  test/PolyhedralGeometry/polyhedral_complex.jl
  test/PolyhedralGeometry/polyhedral_fan.jl
  test/PolyhedralGeometry/polyhedron.jl
  test/PolyhedralGeometry/runtests.jl
  test/PolyhedralGeometry/subdivision_of_points.jl
Labels: enhancement, WIP, renaming

#2396 [ToricVarieties] Bugfixes in toric line bundles
  docs/src/AlgebraicGeometry/ToricVarieties/ToricLineBundles.md
  src/AlgebraicGeometry/ToricVarieties/ToricLineBundles/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/ToricLineBundles/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/ToricLineBundles/special_attributes.jl
  src/AlgebraicGeometry/ToricVarieties/cohomCalg/VanishingSets/methods.jl
  src/AlgebraicGeometry/ToricVarieties/cohomCalg/special_attributes.jl
  src/exports.jl
  test/AlgebraicGeometry/ToricVarieties/line_bundle_cohomologies.jl
  test/AlgebraicGeometry/ToricVarieties/line_bundles.jl
Labels: bug, enhancement, topic: toric varieties
