Repository oscar-system/Oscar.jl, pull requests merged in 2024-02, with the labels that each got.

#3318 Prepare for name printing changes in AA
  src/Rings/MPolyQuo.jl
  src/Rings/mpoly-graded.jl
Labels: package: AbstractAlgebra

#3328 Update qualification of two calls
  src/Modules/UngradedModules/FreeResolutions.jl
Labels: package: Hecke, package: AbstractAlgebra

#3310 Support matrix groups over QQBar
  Project.toml
  src/Groups/matrices/MatGrp.jl
  test/Groups/matrixgroups.jl
Labels: topic: groups

#3309 docs: reorder & regroup permutation groups chapter
  docs/src/Groups/permgroup.md
Labels: documentation, topic: groups

#3255 Adv+ac/phylogenetic trees
  docs/doc.main
  docs/oscar_references.bib
  docs/src/Combinatorics/phylogenetic_trees.md
  src/Combinatorics/Graphs/structs.jl
  src/Combinatorics/PhylogeneticTrees.jl
  src/Oscar.jl
  src/Serialization/Combinatorics.jl
  src/Serialization/polymake.jl
  src/exports.jl
  test/Combinatorics/PhylogeneticTrees.jl
Labels: topic: combinatorics

#3321 Adv/serialize gb
  src/Serialization/Rings.jl
  test/Serialization/PolynomialsSeries.jl
Labels: serialization

#3355 Move printing of banner to its own function
  src/Oscar.jl
Labels: backport 1.0

#3372 adds fix to return non reduced (co)homology
  src/Combinatorics/SimplicialComplexes.jl
  test/Combinatorics/SimplicialComplexes.jl
Labels: backport 1.0

#3291 rename and change some `*_reps` functions
  docs/src/Groups/subgroups.md
  src/Groups/GAPGroups.jl
  src/Groups/GrpAb.jl
  src/Groups/cosets.jl
  src/Groups/gsets.jl
  src/Groups/sub.jl
  src/NumberTheory/GaloisGrp/GaloisGrp.jl
  src/NumberTheory/GaloisGrp/Group.jl
  src/deprecations.jl
  src/exports.jl
  test/Groups/GrpAb.jl
  test/Groups/conjugation.jl
  test/Groups/elements.jl
  test/Groups/matrixgroups.jl
  test/Groups/subgroups_and_cosets.jl
Labels: backport 1.0

#3351 Overhaul root system type detection
  experimental/LieAlgebras/src/AbstractLieAlgebra.jl
  experimental/LieAlgebras/src/CartanMatrix.jl
  experimental/LieAlgebras/src/DynkinDiagram.jl
  experimental/LieAlgebras/src/LieAlgebras.jl
  experimental/LieAlgebras/src/RootSystem.jl
  experimental/LieAlgebras/src/WeylGroup.jl
  experimental/LieAlgebras/test/CartanMatrix-test.jl
  experimental/LieAlgebras/test/DynkinDiagram-test.jl
  experimental/LieAlgebras/test/WeylGroup-test.jl
Labels: merge me, topic: LieAlgebras, backport 1.0

#3365 Make `partitions` and `(semi)standard_tableaux` return iterators
  docs/src/Combinatorics/EnumerativeCombinatorics/partitions.md
  experimental/LieAlgebras/src/Combinatorics.jl
  src/Combinatorics/EnumerativeCombinatorics/partitions.jl
  src/Combinatorics/EnumerativeCombinatorics/tableaux.jl
  test/Combinatorics/EnumerativeCombinatorics/partitions.jl
  test/Combinatorics/EnumerativeCombinatorics/tableaux.jl
Labels: backport 1.0

#3382 Fix Grassmann Pluecker
  src/Rings/mpoly-ideals.jl
Labels: backport 1.0

#3373 Fix show for RelativeBrauerGroupElem
  experimental/GModule/GaloisCohomology.jl
Labels: backport 1.0

#3381 Enable edit and show source buttons in docs
  docs/make_work.jl
  src/utils/utils.jl
Labels: documentation, backport 1.0

#3385 galois_group: fix is_normal call after removed deprecations
  src/NumberTheory/GaloisGrp/GaloisGrp.jl
  test/NumberTheory/galthy.jl
Labels: backport 1.0

#3399 Fix an equality check
  src/Rings/MPolyQuo.jl
Labels: backport 1.0

#3398 Remove unneeded GAP package `sla`
  src/Oscar.jl
Labels: package: GAP, topic: LieAlgebras, backport 1.0

#3402 improve two pieces of documentation
  experimental/GModule/Brueckner.jl
  src/Groups/group_characters.jl
Labels: documentation, topic: groups

#3405 ModStdQt `ref_ff_rc` regression fix
  experimental/ModStd/ModStdQt.jl
  experimental/ModStd/test/ModStdQt.jl
Labels: regression

#2823 Draft - InvRing for SLn
  experimental/InvariantTheory/src/InvariantTheory.jl
  experimental/InvariantTheory/src/TorusInvariantsFast.jl
  experimental/InvariantTheory/test/runtests.jl
Labels: backport 1.0, oscar book

#3374 Hide AbstractAlgebra `ordering` of a polynomial ring (a bit)
  Project.toml
  docs/src/CommutativeAlgebra/rings.md
  examples/ZeroDec.jl
  experimental/GModule/GaloisCohomology.jl
  experimental/GaloisGrp/src/Subfields.jl
  experimental/QuadFormAndIsom/src/embeddings.jl
  experimental/QuadFormAndIsom/src/hermitian_miranda_morrison.jl
  experimental/Schemes/elliptic_surface.jl
  src/AlgebraicGeometry/Surfaces/K3Auto.jl
  src/Groups/matrices/iso_nf_fq.jl
  src/InvariantTheory/types.jl
  src/Modules/UngradedModules/FreeResolutions.jl
  src/Modules/UngradedModules/Presentation.jl
  src/NumberTheory/GaloisGrp/RelGalois.jl
  src/NumberTheory/NmbThy.jl
  src/Rings/NumberField.jl
  src/Rings/PBWAlgebra.jl
  src/Rings/groebner.jl
  src/Rings/mpoly-graded.jl
  src/Rings/mpoly-ideals.jl
  src/Rings/mpoly.jl
  src/exports.jl
  src/imports.jl
  test/InvariantTheory/fundamental_invariants.jl
  test/InvariantTheory/invariant_rings.jl
  test/InvariantTheory/secondary_invariants.jl
  test/Rings/NumberField.jl
  test/Rings/groebner.jl
  test/Rings/mpoly.jl
  test/Rings/orderings.jl
Labels: package: Hecke, package: Nemo, package: AbstractAlgebra, backport 1.0

#3404 Add `all_primitive_groups` and `all_transitive_groups` variants taking a single int or int range
  src/Groups/libraries/primitivegroups.jl
  src/Groups/libraries/transitivegroups.jl
  test/Groups/libraries.jl
Labels: topic: groups

#3412 Corrected defn of deg(ideal); correction from W Decker
  src/Rings/mpoly-graded.jl
Labels: backport 1.0

#3415 Tweak `exterior_algebra` tests
  experimental/ExteriorAlgebra/test/runtests.jl
Labels: backport 1.0

#3422 do not show the OscarInterface banner
  src/Oscar.jl
Labels: package: GAP, backport 1.0

#3421 list the needed GAP packages
  src/Oscar.jl
Labels: package: GAP

#3431 Remove two mentions of `Arb_jll`
  src/Serialization/Fields.jl
Labels: package: Nemo, backport 1.0

#3430 Tweak epimorphism_from_free_group
  src/Groups/sub.jl
Labels: topic: groups, backport 1.0

#3434 Add `all_perfect_groups`
  docs/src/Groups/grouplib.md
  src/Groups/libraries/perfectgroups.jl
  src/exports.jl
  test/Groups/libraries.jl
Labels: enhancement, topic: groups, backport 1.0

#3332 support `gen(G::GAPGroup, 0)`
  src/Groups/GAPGroups.jl
  src/Groups/matrices/MatGrp.jl
  test/Groups/conformance.jl
  test/Groups/elements.jl
Labels: topic: groups, backport 1.0, oscar book

#3436 fix a docstring
  src/Groups/gsets.jl
Labels: backport 1.0

#3396 Fixes multivariate division
  Project.toml
  src/Rings/groebner.jl
  test/Rings/groebner.jl
Labels: topic: rings, package: Singular, backport 1.0

#3428 Docu invariants tori
  docs/doc.main
  docs/src/InvariantTheory/finite_groups.md
  docs/src/InvariantTheory/intro.md
  docs/src/InvariantTheory/tori.md
  experimental/InvariantTheory/src/TorusInvariantsFast.jl
  test/Rings/mpoly-graded.jl
Labels: documentation, backport 1.0

#3437 Bugfix for printing of affine schemes
  experimental/Schemes/MorphismFromRationalFunctions.jl
  src/AlgebraicGeometry/Schemes/AffineSchemes/Objects/Constructors.jl
  src/AlgebraicGeometry/Schemes/AffineSchemes/Objects/Methods.jl
  src/Rings/mpoly-localizations.jl
Labels: backport 1.0

#3432 add docstrings for `acting_group` and `action_function`
  docs/src/Groups/action.md
  src/Groups/gsets.jl
  src/exports.jl
Labels: documentation, topic: groups

#3384 Improve docstrings for `is_conjugate`/`is_conjugate_with_data`.
  src/Groups/GAPGroups.jl
  src/Groups/gsets.jl
Labels: documentation, backport 1.0

#3445 Bugfix for bugfix for printing of affine schemes
  src/AlgebraicGeometry/Schemes/AffineSchemes/Objects/Methods.jl
Labels: backport 1.0

#3448 Fix `ambient_module(M::SubquoModule)`
  src/Modules/UngradedModules/SubquoModule.jl
Labels: backport 1.0

#3410 Update OSCAR banner
  README.md
  src/Oscar.jl
Labels: Decision, backport 1.0

#3449 support group properties for character tables
  docs/src/Groups/basics.md
  docs/src/Groups/group_characters.md
  src/Groups/group_characters.jl
  test/Groups/group_characters.jl
Labels: topic: groups, backport 1.0

#3453 Unexport normalise
  experimental/ModStd/ModStdQt.jl
  src/imports.jl
Labels: package: AbstractAlgebra, backport 1.0

#3444 add `od_from_atlas_group`, `od_from_p_subgroup`, and helpers
  docs/src/Groups/group_characters.md
  experimental/OrthogonalDiscriminants/docs/src/compute.md
  experimental/OrthogonalDiscriminants/src/OrthogonalDiscriminants.jl
  experimental/OrthogonalDiscriminants/src/direct.jl
  experimental/OrthogonalDiscriminants/src/theoretical.jl
  experimental/OrthogonalDiscriminants/src/utils.jl
  experimental/OrthogonalDiscriminants/test/data.jl
  experimental/OrthogonalDiscriminants/test/direct.jl
  experimental/OrthogonalDiscriminants/test/theoretical.jl
  experimental/OrthogonalDiscriminants/test/utils.jl
  src/GAP/wrappers.jl
  src/Groups/group_characters.jl
  src/Groups/libraries/atlasgroups.jl
  src/Groups/matrices/iso_nf_fq.jl
  src/Rings/AbelianClosure.jl
  test/Groups/group_characters.jl
  test/Groups/matrixgroups.jl
Labels: backport 1.0, oscar book

#3443 Docu invariants lin. red. groups (Lakshmi Ramesh and Wolfram Decker)
  docs/src/InvariantTheory/intro.md
  docs/src/InvariantTheory/reductive_groups.md
  experimental/InvariantTheory/src/InvariantTheory.jl
  experimental/InvariantTheory/src/TorusInvariantsFast.jl
  experimental/InvariantTheory/test/runtests.jl
Labels: backport 1.0

#3467 Added comment on convention
  docs/src/InvariantTheory/reductive_groups.md
  experimental/InvariantTheory/src/InvariantTheory.jl
Labels: backport 1.0

#3464 Ensure `fp_group(G)` transfers group attributes
  src/Groups/homomorphisms.jl
  test/Groups/homomorphisms.jl
Labels: topic: groups, backport 1.0

#3458 Export weierstrass_chart_on_minimal_model and patch transform_to_weierstrass
  experimental/Schemes/elliptic_surface.jl
Labels: backport 1.0, oscar book

#3466 Fix a doc signature
  docs/src/NumberTheory/abelian_closure.md
Labels: backport 1.0

#3457 Adjust to renaming of `rank(A::FinGenAbGroup)` to `torsion_free_rank(A::FinGenAbGroup)`
  Project.toml
  experimental/FTheoryTools/src/auxiliary.jl
  experimental/GModule/Cohomology.jl
  experimental/GModule/GaloisCohomology.jl
  src/AlgebraicGeometry/ToricVarieties/NormalToricVarieties/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/NormalToricVarieties/properties.jl
  src/AlgebraicGeometry/ToricVarieties/ToricDivisors/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/ToricMorphisms/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/ToricMorphisms/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/cohomCalg/VanishingSets/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/cohomCalg/auxiliary.jl
  src/Modules/ModulesGraded.jl
  src/Rings/mpoly-graded.jl
  src/imports.jl
  test/AlgebraicGeometry/ToricVarieties/affine_normal_varieties.jl
  test/AlgebraicGeometry/ToricVarieties/del_pezzo_surfaces.jl
  test/AlgebraicGeometry/ToricVarieties/hirzebruch_surfaces.jl
  test/AlgebraicGeometry/ToricVarieties/normal_toric_varieties.jl
  test/AlgebraicGeometry/ToricVarieties/projectivization.jl
  test/AlgebraicGeometry/ToricVarieties/toric_blowdowns.jl
  test/AlgebraicGeometry/ToricVarieties/toric_blowups.jl
  test/AlgebraicGeometry/ToricVarieties/toric_divisor_classes.jl
  test/AlgebraicGeometry/ToricVarieties/total_space.jl
  test/Combinatorics/SimplicialComplexes.jl
  test/Rings/hilbert.jl
Labels: backport 1.0

#3465 Some more uses of GAPWrap
  experimental/GModule/Cohomology.jl
  src/GAP/wrappers.jl
  src/Groups/GAPGroups.jl
  src/Groups/homomorphisms.jl
  src/Groups/matrices/iso_nf_fq.jl
Labels: topic: groups
