Repository oscar-system/Oscar.jl, pull requests merged in 2025-10, with the labels that each got.

#5394 add `_irred_abelian(G::Oscar.GAPGroup, F::FinField)`
  experimental/GModule/src/GModule.jl
  experimental/GModule/test/runtests.jl
Labels: enhancement, topic: groups, release notes: not needed

#5393 Fix regression in enumerate_classes_of_lattices_with_isometry
  src/NumberTheory/QuadFormAndIsom/enumeration.jl
  test/NumberTheory/QuadFormAndIsom.jl
Labels: release notes: not needed

#5339 Methods for group actions on `ZZLat`
  docs/doc.main
  docs/src/NumberTheory/QuadFormAndIsom/fingrpact.md
  docs/src/NumberTheory/QuadFormAndIsom/latwithisom.md
  src/Groups/abelian_aut.jl
  src/Groups/matrices/form_group.jl
  src/NumberTheory/QuadFormAndIsom.jl
  src/NumberTheory/QuadFormAndIsom/embeddings.jl
  src/NumberTheory/QuadFormAndIsom/finite_group_actions.jl
  src/NumberTheory/QuadFormAndIsom/lattices_with_isometry.jl
  src/exports.jl
  test/Groups/abelian_aut.jl
  test/Groups/forms.jl
  test/NumberTheory/QuadFormAndIsom.jl
Labels: enhancement, topic: number theory, release notes: use title

#5404 Move "Combinatorics" docs before "Groups"
  docs/doc.main
Labels: documentation, release notes: not needed

#5410 Intersection theory: More functionality, more examples
  docs/oscar_references.bib
  experimental/IntersectionTheory/docs/doc.main
  experimental/IntersectionTheory/docs/src/ParticularConstructions.md
  experimental/IntersectionTheory/docs/src/intro.md
  experimental/IntersectionTheory/src/IntersectionTheory.jl
  experimental/IntersectionTheory/src/Main.jl
Labels: topic: algebraic geometry, release notes: not needed

#5415 Order experimental modules in documentation
  docs/make_work.jl
Labels: documentation, release notes: not needed

#5418 docs: move "Experimental" before "Index"
  docs/doc.main
  docs/make_work.jl
Labels: documentation, release notes: not needed

#5420 Use `coefficient_ring` in serialization
  src/Serialization/Rings.jl
Labels: serialization, release notes: not needed

#4798 Multigraded Implicitization implementation
  docs/oscar_references.bib
  experimental/AlgebraicStatistics/docs/doc.main
  experimental/AlgebraicStatistics/docs/src/multigraded_implicitization.md
  experimental/AlgebraicStatistics/src/AlgebraicStatistics.jl
  experimental/AlgebraicStatistics/src/DictTypes.jl
  experimental/AlgebraicStatistics/src/MultigradedImplicitization.jl
  experimental/AlgebraicStatistics/test/MultigradedImplicitization.jl
  experimental/Experimental.jl
  experimental/Parallel/src/Parallel.jl
  src/Serialization/parallel.jl
  src/utils/parallel.jl
  test/runtests.jl
Labels: experimental, release notes: use title

#5403 Add `factoring_standard_basis` command which uses `facstd` from `Singular.jl`
  docs/src/CommutativeAlgebra/GroebnerBases/groebner_bases.md
  src/Rings/groebner/factoring.jl
  src/Rings/groebner/groebner.jl
  src/exports.jl
  test/Rings/groebner.jl
Labels: enhancement, triage, topic: algebraic geometry, release notes: use title

#5346 Update assigning File versions
  docs/src/DeveloperDocumentation/serialization.md
  src/Serialization/Upgrades/main.jl
  src/Serialization/main.jl
Labels: serialization, triage, release notes: not needed

#5412 Tweak combinations some more
  docs/src/Combinatorics/EnumerativeCombinatorics/combinations.md
  src/Combinatorics/EnumerativeCombinatorics/combinations.jl
  test/Combinatorics/EnumerativeCombinatorics/combinations.jl
Labels: topic: combinatorics, triage, release notes: not needed

#5413 BasisLieHighestWeight: Allow internal monomial ordering types
  experimental/BasisLieHighestWeight/src/BasisLieHighestWeight.jl
  experimental/BasisLieHighestWeight/src/MainAlgorithm.jl
  experimental/BasisLieHighestWeight/src/MonomialOrder.jl
  experimental/BasisLieHighestWeight/src/UserFunctions.jl
Labels: enhancement, topic: lie theory, release notes: not needed

#5429 added coefficient_ring
  experimental/ActionPolyRing/src/Content.jl
  experimental/ActionPolyRing/src/IO.jl
  experimental/ActionPolyRing/test/ActionPolyRing.jl
Labels: experimental, release notes: not needed

#5428 Fix the docstring of `test_experimental_module`
  src/utils/tests.jl
Labels: documentation, release notes: not needed
