Repository oscar-system/Oscar.jl, pull requests merged in 2025-06, with the labels that each got.

#4950 Fix `minimal_generating_set` for ideals created by a f4 groebner basis
  src/Rings/mpoly-graded.jl
  test/Rings/mpoly-graded.jl
Labels: topic: commutative algebra, release notes: use title, backport 1.4.x

#4952 add a `QQBar` interface to GAP
  gap/pkg/OscarInterface/gap/QQBar.gd
  gap/pkg/OscarInterface/gap/QQBar.gi
  gap/pkg/OscarInterface/gap/alnuth.gi
  gap/pkg/OscarInterface/init.g
  gap/pkg/OscarInterface/julia/constants.jl
  gap/pkg/OscarInterface/read.g
  gap/pkg/OscarInterface/tst/QQBar.tst
  src/Oscar.jl
Labels: enhancement, package: GAP, release notes: use title

#4957 Resolve hash error for FTM-1511-03209 artifact
  Artifacts.toml
Labels: topic: FTheoryTools, release notes: not needed, backport 1.4.x, extra-long

#4961 Remove calls to `groebner_assure`
  src/Rings/NumberField.jl
  src/Rings/groebner/fglm.jl
  src/Rings/groebner/general.jl
  src/Rings/groebner/hilbert-driven.jl
  test/Rings/groebner.jl
Labels: topic: commutative algebra, release notes: not needed

#4965 No longer export misleading `@perm_str` from AA
  docs/src/StraightLinePrograms/intro.md
  src/imports.jl
  test/StraightLinePrograms/atlas.jl
  test/StraightLinePrograms/gap.jl
Labels: package: AbstractAlgebra, release notes: use title

#4966 Replace non-standard whitespace chars
  docs/src/Experimental/intro.md
  gap/pkg/OscarInterface/gap/ExperimentalMatrixGroups.g
  src/Groups/group_characters.jl
  src/Rings/groebner/fglm.jl
  src/Rings/groebner/generators.jl
  test/Rings/MPolyQuo.jl
Labels: release notes: not needed

#4969 extend/correct docu on localization and more
  docs/src/CommutativeAlgebra/affine_algebras.md
  docs/src/CommutativeAlgebra/localizations.md
  src/Modules/UngradedModules/FreeResolutions.jl
  src/Rings/MPolyMap/MPolyQuo.jl
  src/Rings/mpoly-localization_types.jl
  src/Rings/mpoly-localizations.jl
  src/Rings/mpolyquo-localizations.jl
Labels: documentation, topic: commutative algebra

#4979 fix: [`QuadFormAndIsom`] handling of type condition
  experimental/QuadFormAndIsom/src/embeddings.jl
  experimental/QuadFormAndIsom/src/enumeration.jl
  experimental/QuadFormAndIsom/test/runtests.jl
Labels: experimental, release notes: not needed

#4981 Add label checking CI job
  .github/workflows/EnforceLabels.yml
Labels: CI, release notes: not needed

#4985 Reduce `singular_assure` usage further
  examples/PrimDec.jl
  experimental/ModStd/src/ModStdQ.jl
  src/Modules/missing_functionality.jl
  src/Rings/mpoly.jl
Labels: topic: commutative algebra, release notes: not needed

#4989 Fix printing of FreeAssociativeAlgebraIdeals
  src/Rings/FreeAssociativeAlgebraIdeal.jl
Labels: embarrassing-bugfix, release notes: not needed

#4992 Fix loading `FreeAssociativeAlgebraElem`s
  src/Serialization/Algebras.jl
  test/Serialization/Algebras.jl
Labels: serialization, release notes: use title, backport 1.4.x

#4986 Fix upgrades docs
  src/Serialization/Upgrades/main.jl
Labels: serialization, embarrassing-bugfix, release notes: not needed

#4997 Allow loading matrices with nc entries
  src/Serialization/Rings.jl
  src/Serialization/containers.jl
  test/Serialization/Matrices.jl
Labels: serialization, release notes: use title, backport 1.4.x

#4987 Add `natural_gset` method for permutation, matrix & Weyl groups
  examples/BlockSys.jl
  examples/GSets_timing.jl
  experimental/LieAlgebras/src/LieAlgebras.jl
  experimental/LieAlgebras/src/WeylGroup.jl
  experimental/LieAlgebras/test/WeylGroup-test.jl
  src/Groups/gsets.jl
  src/deprecations.jl
  src/exports.jl
  test/Groups/gsets.jl
Labels: topic: groups, release notes: use title

#4999 Add `extraspecial_group` and `is_extraspecial_group`
  docs/src/Groups/basics.md
  docs/src/Groups/pcgroup.md
  src/GAP/wrappers.jl
  src/Groups/group_constructors.jl
  src/exports.jl
  test/Groups/constructors.jl
Labels: enhancement, topic: groups, release notes: use title

#4995 Add `maximal_cliques(::Graph{Undirected})`
  docs/src/Combinatorics/graphs.md
  src/Combinatorics/Graphs/functions.jl
  src/exports.jl
  test/Combinatorics/Graph.jl
Labels: topic: combinatorics, package: Polymake, release notes: use title

#5000 add a remark about a difference between OSCAR and GAP
  docs/src/General/other.md
Labels: documentation, package: GAP, release notes: not needed

#4990 cleanup in the GAP package OscarInterface
  gap/pkg/OscarInterface/gap/OscarInterface.gi
  gap/pkg/OscarInterface/gap/QQBar.gi
  gap/pkg/OscarInterface/gap/alnuth.gi
  gap/pkg/OscarInterface/tst/QQBar.tst
Labels: enhancement, topic: number theory, package: GAP, release notes: not needed

#4984 Replace `oscar_assure` by `oscar_generators`
  experimental/InjectiveResolutions/src/InjectiveResolutions.jl
  experimental/InjectiveResolutions/src/ModuleFunctionality.jl
  experimental/ModStd/src/ModStdNF.jl
  src/Modules/UngradedModules/ModuleGens.jl
  src/Modules/UngradedModules/SubModuleOfFreeModule.jl
  src/Modules/UngradedModules/SubquoModule.jl
  src/Modules/UngradedModules/SubquoModuleElem.jl
  src/Rings/MPolyQuo.jl
  src/Rings/groebner/f4.jl
  src/Rings/groebner/generators.jl
  src/Rings/groebner/reduce.jl
  src/Rings/mpoly-ideals.jl
  src/Rings/mpoly.jl
  src/Rings/solving.jl
  test/Modules/ModulesGraded.jl
  test/Modules/UngradedModules.jl
  test/Rings/MPolyQuo.jl
  test/Rings/groebner.jl
Labels: topic: commutative algebra, release notes: not needed

#5004 Print sheaf cohomology tables more compactly
  src/Modules/ModulesGraded.jl
  test/book/cornerstones/algebraic-geometry/char3-surface-2.jlcon
Labels: printing, release notes: use title

#5008 Intersection theory: Pass along attribute `:alg` in `projective_bundle`, more in docu
  experimental/IntersectionTheory/docs/src/AbstractVarieties.md
  experimental/IntersectionTheory/docs/src/intro.md
  experimental/IntersectionTheory/src/Main.jl
  src/Rings/MPolyQuo.jl
Labels: topic: algebraic geometry, release notes: not needed

#5005 feat [`QuadFormAndIsom`]: more flexible inputs for functions with parameters
  experimental/QuadFormAndIsom/src/embeddings.jl
  experimental/QuadFormAndIsom/src/enumeration.jl
  experimental/QuadFormAndIsom/test/runtests.jl
Labels: experimental, release notes: not needed

#5011 Add `natural_gset` to group action documentation
  docs/src/Groups/action.md
Labels: documentation, release notes: not needed

#4968 Replace `AbstractAlgebra.combinations`
  experimental/FTheoryTools/src/FamilyOfSpaces/attributes.jl
  experimental/IntersectionTheory/src/Bott.jl
  experimental/IntersectionTheory/src/IntersectionTheory.jl
  src/TropicalGeometry/linear_space.jl
  src/deprecations.jl
Labels: release notes: not needed

#5014 Replace some uses of '@attr Any'
  src/AlgebraicGeometry/Schemes/PrincipalOpenSubset/Objects/Properties.jl
  src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl
  src/Modules/mpolyquo.jl
Labels: release notes: not needed

#5017 Chern classes can be serialized
  experimental/FTheoryTools/src/AbstractFTheoryModels/attributes.jl
  experimental/FTheoryTools/src/Serialization/hypersurface_models.jl
  experimental/FTheoryTools/src/Serialization/tate_models.jl
  experimental/FTheoryTools/src/Serialization/weierstrass_models.jl
  experimental/FTheoryTools/test/QSMs.jl
  src/AlgebraicGeometry/ToricVarieties/CohomologyClasses/constructors.jl
  src/AlgebraicGeometry/ToricVarieties/CohomologyClasses/special_attributes.jl
  test/Serialization/ToricGeometry.jl
Labels: topic: toric geometry, serialization, topic: FTheoryTools, release notes: use title

#4988 New implementation of `map_from_func` with changed argument order
  experimental/IntersectionTheory/src/IntersectionTheory.jl
  experimental/IntersectionTheory/src/Main.jl
  experimental/IntersectionTheory/src/Types.jl
  experimental/IntersectionTheory/src/blowup.jl
  src/AlgebraicGeometry/Surfaces/EllipticSurface/Morphisms.jl
  src/Groups/abelian_aut.jl
  src/Misc/MapFromFunc.jl
  src/Misc/Misc.jl
  src/exports.jl
  src/imports.jl
Labels: release notes: use title

#5018 Resolution cleanup, round two
  experimental/DoubleAndHyperComplexes/src/Morphisms/Types.jl
  experimental/DoubleAndHyperComplexes/src/Morphisms/free_resolutions.jl
  experimental/DoubleAndHyperComplexes/src/Morphisms/simplified_complexes.jl
  experimental/DoubleAndHyperComplexes/src/Objects/Methods.jl
  experimental/DoubleAndHyperComplexes/test/linear_strands.jl
  experimental/DoubleAndHyperComplexes/test/tensor_products.jl
  src/Modules/UngradedModules/FreeResolutions.jl
Labels: topic: commutative algebra, release notes: not needed

#4858 Improve GModule support for ModuleFP
  experimental/GModule/src/Cohomology.jl
  experimental/GModule/src/GModule.jl
Labels: experimental, release notes: not needed

#5027 Fix bug in mres
  src/Modules/UngradedModules/Presentation.jl
  test/Modules/UngradedModules.jl
Labels: bug, release notes: not needed

#5029 Update test following PR #5027
  test/Modules/UngradedModules.jl
Labels: topic: commutative algebra, release notes: not needed

#5030 Deprecate `vector_space_dimension`, use `vector_space_dim` instead
  docs/src/CommutativeAlgebra/affine_algebras.md
  experimental/DoubleAndHyperComplexes/test/LeGreuelFormulaOnStratifiedSpaces.jl
  experimental/InvariantTheory/src/InvariantTheory.jl
  experimental/InvariantTheory/test/runtests.jl
  experimental/Schemes/src/Resolution_structure.jl
  experimental/Schemes/src/Resolution_tools.jl
  experimental/Schemes/src/SpaceGerms.jl
  experimental/Schemes/src/Tjurina.jl
  src/AlgebraicGeometry/Curves/AffinePlaneCurve.jl
  src/AlgebraicGeometry/Schemes/AffineSchemes/Objects/Attributes.jl
  src/AlgebraicGeometry/Schemes/AffineSchemes/SimplifiedAffineScheme/Methods.jl
  src/AlgebraicGeometry/Surfaces/duValSing.jl
  src/Modules/UngradedModules/Methods.jl
  src/Rings/mpoly-affine-algebras.jl
  src/Rings/mpolyquo-localizations.jl
  src/deprecations.jl
  src/exports.jl
  test/Modules/UngradedModules.jl
  test/Rings/mpoly-affine-algebras.jl
  test/book/cornerstones/algebraic-geometry/twocusps.jlcon
  test/book/cornerstones/algebraic-geometry/zariski.jlcon
Labels: topic: commutative algebra, release notes: use title
