Repository oscar-system/Oscar.jl, pull requests merged in 2025-09, with the labels that each got.

#5263 [FTheoryTools] Minor improvement
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/methods.jl
  experimental/FTheoryTools/test/paper_tests.jl
Labels: optimization, topic: FTheoryTools, release notes: not needed, extra-long

#5226 Update to GAP.jl 0.15
  Project.toml
  src/GAP/gap_to_oscar.jl
  src/GAP/oscar_to_gap.jl
  test/GAP/gap_to_oscar.jl
  test/GAP/oscar_to_gap.jl
Labels: package: GAP, release notes: use title

#5260 Allow permutation matrices over non-commutative rings
  docs/src/Groups/matgroup.md
  src/Groups/matrices/matrix_manipulation.jl
Labels: enhancement, topic: groups, release notes: not needed

#4928 Use symbols instead of strings for variables in toric geometry
  docs/src/AlgebraicGeometry/ToricVarieties/BlowupMorphisms.md
  experimental/FTheoryTools/src/AbstractFTheoryModels/Methods/blowups.jl
  experimental/FTheoryTools/src/auxiliary.jl
  experimental/Schemes/src/ToricBlowups/constructors.jl
  experimental/Schemes/src/ToricBlowups/types.jl
  experimental/Schemes/test/runtests.jl
  src/AlgebraicGeometry/ToricVarieties/NormalToricVarieties/attributes.jl
  src/AlgebraicGeometry/ToricVarieties/cohomCalg/auxiliary.jl
  test/AlgebraicGeometry/ToricVarieties/del_pezzo_surfaces.jl
  test/AlgebraicGeometry/ToricVarieties/hirzebruch_surfaces.jl
  test/AlgebraicGeometry/ToricVarieties/projective_spaces.jl
  test/AlgebraicGeometry/ToricVarieties/toric_blowups.jl
Labels: topic: toric geometry, optimization, release notes: use title, extra-long

#5281 Update Singular.jl to 0.26
  Project.toml
Labels: package: Singular, release notes: use title

#4570 BasisLieHightestWeight: Extend functionality to Demazure modules
  experimental/BasisLieHighestWeight/src/BasisLieHighestWeight.jl
  experimental/BasisLieHighestWeight/src/LieAlgebras.jl
  experimental/BasisLieHighestWeight/src/MainAlgorithm.jl
  experimental/BasisLieHighestWeight/src/ModuleData.jl
  experimental/BasisLieHighestWeight/src/MonomialBasis.jl
  experimental/BasisLieHighestWeight/src/UserFunctions.jl
  experimental/BasisLieHighestWeight/src/WeylPolytope.jl
  experimental/BasisLieHighestWeight/test/MainAlgorithm-test.jl
Labels: topic: lie theory, experimental, release notes: use title

#5247 Consolidate `id_hom` and `identity_map`
  experimental/LieAlgebras/docs/src/lie_algebra_homs.md
  experimental/LieAlgebras/docs/src/module_homs.md
  experimental/LieAlgebras/src/LieAlgebraHom.jl
  experimental/LieAlgebras/src/LieAlgebraModuleHom.jl
  experimental/LieAlgebras/src/LieAlgebras.jl
  experimental/LieAlgebras/test/LieAlgebraHom-test.jl
  experimental/LieAlgebras/test/LieAlgebraModule-test.jl
  experimental/LieAlgebras/test/LieAlgebraModuleHom-test.jl
  src/Groups/GAPGroups.jl
  src/Groups/GrpAb.jl
  src/Groups/action.jl
  src/Groups/group_characters.jl
  src/Groups/homomorphisms.jl
  src/Modules/ModulesGraded.jl
  src/Modules/UngradedModules/FreeMod.jl
  src/Modules/UngradedModules/FreeModuleHom.jl
  src/Modules/UngradedModules/FreeResolutions.jl
  src/Modules/UngradedModules/HomologicalAlgebra.jl
  src/Modules/UngradedModules/Methods.jl
  src/Modules/UngradedModules/Presentation.jl
  src/Modules/hilbert.jl
  src/Modules/local_rings.jl
  src/Rings/mpoly-affine-algebras.jl
  src/Rings/mpoly-localizations.jl
  src/Rings/mpolyquo-localizations.jl
  src/Rings/primary_decomposition_helpers.jl
  test/Modules/ModulesGraded.jl
  test/Modules/UngradedModules.jl
  test/Modules/flattenings.jl
  test/Rings/mpolyquo-localizations.jl
Labels: renaming, release notes: not needed

#5282 chore: update AA to 0.47, Nemo to 0.52, and Hecke to 0.38
  Project.toml
  docs/src/NumberTheory/abelian_closure.md
  docs/src/Rings/integer.md
  experimental/GModule/src/Brueckner.jl
  experimental/GModule/src/Cohomology.jl
  experimental/GModule/src/GModule.jl
  experimental/GModule/src/GaloisCohomology.jl
  experimental/GaloisGrp/src/Solve.jl
  experimental/GaloisGrp/src/Subfields.jl
  experimental/StandardFiniteFields/src/StandardFiniteFields.jl
  gap/pkg/OscarInterface/gap/QQBar.gi
  gap/pkg/OscarInterface/tst/QQBar.tst
  src/NumberTheory/GaloisGrp/GaloisGrp.jl
  src/NumberTheory/GaloisGrp/Qt.jl
  src/NumberTheory/NmbThy.jl
  src/NumberTheory/QuadFormAndIsom/lattices_with_isometry.jl
  src/PolyhedralGeometry/Polyhedron/standard_constructions.jl
  src/Rings/AbelianClosure.jl
  src/Rings/AlgClosureFp.jl
  src/Rings/MPolyMap/MPolyAnyMap.jl
  src/Rings/mpoly-affine-algebras.jl
  src/Rings/mpoly-graded.jl
  src/Rings/solving.jl
  test/book/cornerstones/algebraic-geometry/circlepar.jlcon
  test/book/cornerstones/algebraic-geometry/monodromy.jlcon
  test/book/cornerstones/groups/intro.jlcon
  test/book/cornerstones/number-theory/intro-v1.13.jlcon
  test/book/cornerstones/number-theory/intro.jlcon
  test/book/cornerstones/number-theory/sym.jlcon
  test/book/specialized/eder-mohr-ideal-theoretic/combinatorics.jlcon
  test/book/specialized/kuehne-schroeter-matroids/ChowRings.jlcon
Labels: package: Hecke, package: Nemo, package: AbstractAlgebra, release notes: to be added

#5294 chore: set version to 1.6.0-DEV
  Project.toml
  README.md
  gap/pkg/OscarInterface/PackageInfo.g
Labels: release notes: not needed

#5229 Adds internal islattice check for Ideals
  src/Rings/binomial_ideals.jl
  src/Rings/groebner/general.jl
Labels: topic: commutative algebra, release notes: not needed

#5324 Fix typo in documentation
  docs/src/AlgebraicGeometry/AlgebraicSets/AffineAlgebraicSet.md
  src/Groups/group_constructors.jl
Labels: release notes: not needed

#5322 fix coordinates command in mpoly_localizations (Resolves issue #5316)
  src/Rings/mpoly-localizations.jl
  test/Rings/mpoly-localizations.jl
Labels: release notes: not needed

#5327 fix access to a `Fac` object
  src/Rings/FinField.jl
  test/Rings/FinField.jl
Labels: release notes: not needed, bug: unexpected error, backport 1.5.x

#5336 Rename variable in an example
  docs/src/Groups/fpgroup.md
Labels: documentation, topic: groups, release notes: not needed, summer-school-2025

#5333 FTheoryTools: add ensure_qsmdb_installed()
  experimental/FTheoryTools/src/AbstractFTheoryModels/Attributes/computed_attributes.jl
  experimental/FTheoryTools/src/AbstractFTheoryModels/Attributes/not_yet_computed_attributes.jl
  experimental/FTheoryTools/src/AbstractFTheoryModels/Attributes/precomputed_attributes.jl
  experimental/FTheoryTools/src/AbstractFTheoryModels/Attributes/qsm_attributes.jl
  experimental/FTheoryTools/src/AbstractFTheoryModels/Properties/properties.jl
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/attributes.jl
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/constructors.jl
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/methods.jl
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/properties.jl
  experimental/FTheoryTools/src/FamilyOfG4Fluxes/special_constructors.jl
  experimental/FTheoryTools/src/G4Fluxes/attributes.jl
  experimental/FTheoryTools/src/G4Fluxes/auxiliary.jl
  experimental/FTheoryTools/src/G4Fluxes/constructors.jl
  experimental/FTheoryTools/src/G4Fluxes/properties.jl
  experimental/FTheoryTools/src/auxiliary.jl
Labels: topic: FTheoryTools, release notes: not needed

#5344 Format some files
  test/AlgebraicGeometry/ToricVarieties/algebraic_cycles.jl
  test/AlgebraicGeometry/ToricVarieties/intersection_numbers.jl
  test/AlgebraicGeometry/ToricVarieties/line_bundles.jl
  test/AlgebraicGeometry/ToricVarieties/subvarieties.jl
  test/AlgebraicGeometry/ToricVarieties/toric_blowups.jl
  test/AlgebraicGeometry/ToricVarieties/toric_divisor_classes.jl
  test/AlgebraicGeometry/ToricVarieties/toric_divisors.jl
  test/AlgebraicGeometry/ToricVarieties/toric_morphisms.jl
  test/AlgebraicGeometry/ToricVarieties/toric_schemes.jl
  test/PolyhedralGeometry/cone.jl
  test/PolyhedralGeometry/extended.jl
  test/PolyhedralGeometry/iterators.jl
  test/PolyhedralGeometry/polyhedral_complex.jl
  test/PolyhedralGeometry/polyhedral_fan.jl
  test/PolyhedralGeometry/polyhedron.jl
  test/PolyhedralGeometry/setup_tests.jl
  test/PolyhedralGeometry/subdivision_of_points.jl
  test/PolyhedralGeometry/types.jl
Labels: release notes: not needed

#5338 LatticesWithIsometry up to local equivalence.
  src/NumberTheory/QuadFormAndIsom/embeddings.jl
  src/NumberTheory/QuadFormAndIsom/enumeration.jl
  src/NumberTheory/QuadFormAndIsom/lattices_with_isometry.jl
  test/NumberTheory/QuadFormAndIsom.jl
Labels: topic: number theory, release notes: not needed

#5288 Add `p_rump` for `GAPGroup` and extend `torsion_subgroup` for `GAPGroup` and `WeylGroup`
  docs/src/Groups/subgroups.md
  experimental/LieAlgebras/src/LieAlgebras.jl
  experimental/LieAlgebras/src/WeylGroup.jl
  experimental/LieAlgebras/test/WeylGroup-test.jl
  src/GAP/wrappers.jl
  src/Groups/GAPGroups.jl
  src/exports.jl
  test/Groups/subgroups_and_cosets.jl
Labels: enhancement, topic: groups, release notes: use title

#5311 Modify code formatting logic
  .github/workflows/JuliaFormatterCI.yml
  etc/format_code.jl
  etc/test_formatting.jl
Labels: optimization, release notes: not needed

#5325 Fix too much caching
  experimental/GModule/src/Misc.jl
Labels: bug, topic: commutative algebra, release notes: not needed, backport 1.5.x, summer-school-2025

#5350 Add hint how to run `format_code.jl`
  etc/format_code.jl
Labels: release notes: not needed, summer-school-2025

#5334 GModule fixes from the summer school
  experimental/GModule/docs/doc.main
  experimental/GModule/docs/src/intro.md
  experimental/GModule/src/Cohomology.jl
  experimental/GModule/src/GModule.jl
  experimental/GModule/src/GaloisCohomology.jl
  experimental/GModule/src/GrpExt.jl
  experimental/GModule/src/MeatAxe.jl
  experimental/GModule/src/Misc.jl
Labels: optimization, release notes: not needed

#5351 Fix indentation and numbering in `printing_details.md`
  docs/src/DeveloperDocumentation/printing_details.md
Labels: documentation, release notes: not needed, backport 1.5.x, summer-school-2025

#5361 use Hecke's `coprime_residues`
  src/Groups/schur_index.jl
Labels: topic: groups, release notes: not needed

#5315 Fix bugs found by JET
  docs/make.jl
  docs/make_work.jl
  experimental/Experimental.jl
  experimental/GModule/src/Cohomology.jl
  src/Rings/FinField.jl
  src/Rings/groebner/reduce.jl
  src/Rings/mpoly.jl
  src/aliases.jl
Labels: release notes: not needed

#5367 Speed up admissible_triples in QuadFormWithIsom
  src/NumberTheory/QuadFormAndIsom/enumeration.jl
Labels: topic: number theory, release notes: not needed

#5332 Fix compatibility conditions for groups and group elements
  docs/src/Groups/grouphom.md
  experimental/GModule/src/Cohomology.jl
  experimental/GModule/test/runtests.jl
  src/Groups/GAPGroups.jl
  src/Groups/homomorphisms.jl
  test/Groups/homomorphisms.jl
Labels: topic: groups, release notes: not needed, bug: unexpected error

#5369 Use joinpath to create paths, not hard coded slash '/'
  docs/make_work.jl
  etc/check_docstrings.jl
  experimental/Experimental.jl
  experimental/FTheoryTools/src/AbstractFTheoryModels/Attributes/basic_attributes.jl
  experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl
  experimental/FTheoryTools/src/LiteratureModels/constructors.jl
  experimental/FTheoryTools/src/LiteratureModels/create_index.jl
  experimental/OrthogonalDiscriminants/src/data.jl
  src/AlgebraicGeometry/Surfaces/EnriquesAut.jl
  src/utils/docs.jl
  test/AlgebraicGeometry/ToricVarieties/toric_blowups.jl
  test/book/test.jl
Labels: release notes: not needed

#5379 Allow reseting the variable name of QQAbField
  src/Rings/AbelianClosure.jl
  test/Rings/AbelianClosure.jl
Labels: release notes: not needed

#5384 polyhedral geometry: doc enhancements and further functions inherited from polymake
  docs/oscar_references.bib
  docs/src/PolyhedralGeometry/Polyhedra/auxiliary.md
  src/PolyhedralGeometry/Polyhedron/properties.jl
  src/exports.jl
Labels: enhancement, topic: polyhedral geometry, merge me, release notes: use title
